<?php
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;

/**
 * Implements hook_entity_form_display_alter().
 */
function helfi_ahjo_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context)
{
  if ($context['entity_type'] == 'taxonomy_term' && $context['form_mode'] == 'default') {
    $form_display
      ->setComponent('field_external_id', [
        'region' => 'content',
      ])
      ->setComponent('field_external_parent_id', [
        'region' => 'content',
      ]);
  }
}

/**
 * Implements hook_theme().
 */
function helfi_ahjo_theme($existing, $type, $theme, $path) {
  return [
    'hierarchical_taxonomy_menu' => [
      'variables' => [
        'menu_tree' => [],
        'route_tid' => NULL,
        'vocabulary' => NULL,
        'current_depth' => 0,
        'max_depth' => 0,
        'collapsible' => NULL,
      ],
    ],
  ];

}
